/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.shuozhao.rpn;

import java.util.Scanner;

public class App {

    private Scanner input;
    private Calculator calculator;

    public App() {
        this.input = new Scanner(System.in);
        this.calculator = new Calculator();
    }

    private String scan() {
        return input.nextLine();
    }

    public void start() {
        System.out.println("Please start input parameters: (q to quit)");
        UserInputProcessor processor = new UserInputProcessor(calculator);
        while(true) {
            String line = scan();
            if (line.equals("q")) {
                break;
            } else {
                ProcessResult result = processor.process(line);
                if (result.hasError()) {
                    System.out.println(result.getError());
                }
                System.out.println("stack: " + result.getResult());
            }
        }
    }

    public static void main(String[] args) {
        App app = new App();
        app.start();
    }
}
